[project]
name = "dinnyesmerci"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "structlog>=25.4.0",
    "tenacity>=9.1.2",
]
