line-length = 120
indent-width = 4
target-version = "py311"


exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".vscode",
    ".mypy_cache",
    ".vscode",
    "*.txt",
]

[lint]
select = ["ALL"]
ignore = [
    "I001",     # import sorting
    "ANN204",   # init return type annotation
    "COM812",   # 
    "D107",     # init docsstring
    "D211",     # no-blank-line-before-class
    "D213",     # multi-line-summary-second-line
    "T201",     # print
    "ERA001",   # code in comment
    "N806",     # UPPERCASE vars
    "BLE001",   # Do not catch blind exception: `Exception`
    "FBT001",   # Boolean-typed positional argument in function definition
    "FBT002",   # Boolean default positional argument in function definition
    "PGH004",   # use top noqa
    ]

extend-select = ["E501"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = [
    "W293",
    "COM812",
    "D300",     # triple double quotes for docstrings
    "Q002",     # -||-
    "Q000",     # single quotes instead of double quotes
    ]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"