line-length = 180
indent-width = 4
target-version = "py313"


exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".vscode",
    ".mypy_cache",
    ".vscode",
    "*.txt",
]

[lint]
select = ["ALL"]
ignore = [
    "SIM300",   # allow Yoda condition
    "I001",     # import sorting
    "ANN204",   # init return type annotation
    "ANN401",   # allow Any
    "COM812",   # sanyi
    "D107",     # init docsstring
    "D211",     # no-blank-line-before-class
    "D213",     # multi-line-summary-second-line
    # "T201",     # print
    "E501",     # line too long..
    "G004",      # allow f string in logs (structlog)
    "PLC0206",  # dict keys
    "ANN001",   # allow Any
    "TD002",    # TODO stuff
    "TD003",    # TODO stuff
    "FIX002",   # TODO stuff
    "ERA001",   # code in comment
    "N806",     # UPPERCASE vars
    "BLE001",   # Do not catch blind exception: `Exception`
    "FBT001",   # Boolean-typed positional argument in function definition
    "FBT002",   # Boolean default positional argument in function definition
    "PGH004",   # use top noqa
    ]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = [
    "W293",
    "COM812",
    "D300",     # triple double quotes for docstrings
    "Q002",     # -||-
    "Q000",     # single quotes instead of double quotes
    ]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"